# Generated by Django 2.2.2 on 2019-06-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='psaawd',
            new_name='passwd',
        ),
    ]
