# Generated by Django 2.2.2 on 2019-06-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_auto_20190626_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=64)),
                ('ISBN', models.CharField(max_length=16)),
                ('publisher', models.CharField(max_length=64)),
                ('booknum', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userinfor',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
