# Generated by Django 2.2.2 on 2019-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_auto_20190628_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfor',
            name='ISBN',
            field=models.CharField(max_length=32),
        ),
    ]
