# Generated by Django 2.2.2 on 2019-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_auto_20190701_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfor',
            name='author',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='bookinfor',
            name='booknum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='sex',
            field=models.CharField(max_length=4),
        ),
    ]
